export const SCOPES={calendar:'https://www.googleapis.com/auth/calendar.readonly',gmail:'https://www.googleapis.com/auth/gmail.metadata'};
export function validClientId(value){return /^[\w-]+\.apps\.googleusercontent\.com$/.test(value);}
export function mailSummary(message){const headers=message.payload?.headers||[];const get=name=>headers.find(h=>h.name.toLowerCase()===name.toLowerCase())?.value||'';return {id:message.id,subject:get('Subject')||'(Senza oggetto)',from:get('From'),date:get('Date')};}
export function createGoogle({fetcher=fetch,onChange=()=>{}}={}){
 const sessions={},data={calendar:[],gmail:[]},errors={},updated={},busy={};let generation=0,loading;
 function load(){if(globalThis.google?.accounts?.oauth2)return Promise.resolve();if(loading)return loading;loading=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=()=>resolve();script.onerror=()=>{loading=null;script.remove();reject(Error('Impossibile caricare Google. Controlla la connessione.'));};document.head.append(script);});return loading;}
 function connected(kind){return !!sessions[kind]&&sessions[kind].expires>Date.now();}
 async function request(kind,url){if(!connected(kind))throw Error('Sessione scaduta: premi Collega per autorizzare nuovamente.');const response=await fetcher(url,{headers:{Authorization:'Bearer '+sessions[kind].token},cache:'no-store'});if(!response.ok){if(response.status===401){delete sessions[kind];data[kind]=[];}throw Error(response.status===403?'Accesso negato: verifica API abilitate e permessi Google.':'Richiesta Google non riuscita ('+response.status+'). Riprova.');}return response.json();}
 async function refresh(kind,calendarId='primary',labels='INBOX'){if(busy[kind])return;const gen=generation;busy[kind]=true;errors[kind]='';onChange();try{let result;if(kind==='calendar'){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+7);const q=new URLSearchParams({timeMin:start.toISOString(),timeMax:end.toISOString(),singleEvents:'true',orderBy:'startTime',maxResults:'100'});const r=await request(kind,'https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(calendarId)+'/events?'+q);result=(r.items||[]).filter(e=>e.status!=='cancelled');if(r.nextPageToken)errors[kind]='Mostrati i primi 100 eventi della settimana.';}else{const q=new URLSearchParams({maxResults:'15',labelIds:labels});const r=await request(kind,'https://gmail.googleapis.com/gmail/v1/users/me/messages?'+q);result=await Promise.all((r.messages||[]).map(async m=>mailSummary(await request(kind,'https://gmail.googleapis.com/gmail/v1/users/me/messages/'+encodeURIComponent(m.id)+'?format=metadata&metadataHeaders=Subject&metadataHeaders=From&metadataHeaders=Date'))));}if(gen===generation){data[kind]=result;updated[kind]=new Date().toLocaleTimeString('it-IT');}}catch(e){if(gen===generation){errors[kind]=e.message;data[kind]=[];}}finally{if(gen===generation){busy[kind]=false;onChange();}}}
 function connect(kind,clientId,calendarId,labels){if(!validClientId(clientId)){errors[kind]='Inserisci un Client ID OAuth web valido.';onChange();return;}if(!globalThis.google?.accounts?.oauth2){errors[kind]='Google si sta caricando: attendi e premi nuovamente Collega.';load().catch(e=>{errors[kind]=e.message;onChange();});onChange();return;}const gen=generation;const client=google.accounts.oauth2.initTokenClient({client_id:clientId,scope:SCOPES[kind],include_granted_scopes:false,callback:r=>{if(gen!==generation)return;if(r.error||!r.access_token||!google.accounts.oauth2.hasGrantedAllScopes(r,SCOPES[kind])){errors[kind]='Autorizzazione non concessa.';onChange();return;}sessions[kind]={token:r.access_token,expires:Date.now()+Number(r.expires_in||3600)*1000-30000};refresh(kind,calendarId,labels);},error_callback:()=>{errors[kind]='Finestra Google chiusa o bloccata. Riprova in Chrome o Safari.';onChange();}});client.requestAccessToken({prompt:'select_account'});}
 function disconnect(){generation++;for(const k of Object.keys(SCOPES)){delete sessions[k];data[k]=[];errors[k]='';updated[k]='';busy[k]=false;}onChange();}
 return {load,connect,refresh,disconnect,connected,data,errors,updated,busy};
}
