import {areas,blankDay,areaScore,dailyScore,localDate,shiftDate,validDay} from './legacy-model.js';
const archiveStorage=new URLSearchParams(location.search).has('sandbox')?sessionStorage:localStorage;
const $=id=>document.getElementById(id),key='life-os:v1';let days={},date=localDate(),day,storageOk=true;
try{const raw=archiveStorage.getItem(key);try{const v2=JSON.parse(archiveStorage.getItem('life-os:v2')||'null');if(v2?.legacyDays&&Object.values(v2.legacyDays).every(validDay))days=v2.legacyDays;}catch{}if(raw){const parsed=JSON.parse(raw);if(parsed.version!==1||!parsed.days||Object.entries(parsed.days).some(([d,v])=>!/^\d{4}-\d{2}-\d{2}$/.test(d)||!validDay(v)))throw Error('invalid');days={...days,...parsed.days};}}catch{storageOk=false;$('save-status').textContent='Archivio non leggibile · modifiche non salvate';}
$('areas').innerHTML=areas.map((a,i)=>`<section class="card area ${a.id}"><div class="area-heading"><span class="area-icon" aria-hidden="true">${a.symbol}</span><span class="area-number">0${i+1}</span></div><div class="area-title"><h2>${a.name}</h2><span id="${a.id}-score">0%</span></div><p>${a.subtitle}</p><div class="progress"><span id="${a.id}-progress"></span></div><div class="metrics">${a.fields.map(([id,label,unit,target,step])=>`<label class="metric" for="${id}"><span>${label}</span><div><input id="${id}" type="number" min="0" step="${step}" placeholder="0" data-value="${id}"><span>${unit}</span></div><small>${target===null?'Solo monitoraggio':`Target: ${target.toLocaleString('it-IT')} ${unit}`}</small></label>`).join('')}</div><div class="habits">${a.habits.map(([id,label])=>`<label class="check"><input type="checkbox" id="${id}" data-habit="${id}"><span>${label}</span></label>`).join('')}</div></section>`).join('');
function persist(){days[date]=day;if(!storageOk)return;try{archiveStorage.setItem(key,JSON.stringify({version:1,days}));$('save-status').textContent='Salvato · su questo browser';}catch{$('save-status').textContent='Salvataggio non riuscito · esporta un backup';}}
function updateScore(){const score=dailyScore(day);$('score').textContent=score;$('score-ring').style.setProperty('--score',score+'%');$('score-message').textContent=score>=80?'Una bella giornata.':score>=40?'Stai trovando il ritmo.':'Si parte da qui.';areas.forEach(a=>{const value=areaScore(a,day);$(a.id+'-score').textContent=value+'%';$(a.id+'-progress').style.width=value+'%';});$('journal-count').textContent=day.journal.length+' caratteri';}
function load(selected){date=selected;day=days[date]||blankDay();$('date').value=date;const d=new Date(date+'T12:00:00');$('weekday').textContent=d.toLocaleDateString('it-IT',{weekday:'long'});$('date-title').textContent=d.toLocaleDateString('it-IT',{day:'numeric',month:'long',year:'numeric'});document.querySelectorAll('[data-value]').forEach(el=>el.value=day.values[el.dataset.value]??'');document.querySelectorAll('[data-habit]').forEach(el=>el.checked=Boolean(day.habits[el.dataset.habit]));$('big-thing').value=day.bigThing;$('big-done').checked=day.bigDone;$('journal').value=day.journal;const monday=shiftDate(date,-((d.getDay()+6)%7));$('week-strip').replaceChildren(...Array.from({length:7},(_,i)=>{const current=shiftDate(monday,i),button=document.createElement('button');button.className=current===date?'selected':'';button.setAttribute('aria-label',new Date(current+'T12:00:00').toLocaleDateString('it-IT',{dateStyle:'full'}));button.setAttribute('aria-pressed',String(current===date));button.innerHTML=`<span>${['L','M','M','G','V','S','D'][i]}</span><strong>${Number(current.slice(-2))}</strong><i class="${days[current]?'recorded':''}"></i>`;button.onclick=()=>load(current);return button;}));updateScore();}
$('daily-view').addEventListener('input',e=>{const el=e.target;if(el.dataset.value){if(!el.validity.valid)return;day.values[el.dataset.value]=el.value===''?'':Number(el.value);}else if(el.dataset.habit)day.habits[el.dataset.habit]=el.checked;else if(el.id==='big-thing')day.bigThing=el.value;else if(el.id==='big-done')day.bigDone=el.checked;else if(el.id==='journal')day.journal=el.value;else return;persist();updateScore();});
$('date').onchange=e=>{if(e.target.value&&e.target.validity.valid)load(e.target.value);};$('previous').onclick=()=>load(shiftDate(date,-1));$('next').onclick=()=>load(shiftDate(date,1));$('today').onclick=()=>load(localDate());
function view(history){$('daily-view').hidden=history;$('history-view').hidden=!history;$('daily-nav').classList.toggle('active',!history);$('history-nav').classList.toggle('active',history);$('page-name').textContent=history?'Storico':'Daily Dashboard';if(history)renderHistory();}
function renderHistory(){const entries=Object.entries(days).sort(([a],[b])=>b.localeCompare(a));$('history-summary').textContent=`${entries.length} giornate registrate · Score medio ${entries.length?Math.round(entries.reduce((sum,[,v])=>sum+dailyScore(v),0)/entries.length):0}/100`;$('history-list').replaceChildren();if(!entries.length){$('history-list').textContent='Il tuo percorso inizia oggi. Compila un campo per salvare la prima giornata.';return;}entries.forEach(([date,value])=>{const button=document.createElement('button');button.className='history-row';const label=document.createElement('span');label.textContent=new Date(date+'T12:00:00').toLocaleDateString('it-IT',{dateStyle:'long'});const text=document.createElement('span');text.textContent=value.bigThing||'Nessuna priorità annotata';const score=document.createElement('strong');score.textContent=dailyScore(value)+'/100 →';button.append(label,text,score);button.onclick=()=>{load(date);view(false);};$('history-list').append(button);});}
$('daily-nav').onclick=()=>view(false);$('history-nav').onclick=()=>view(true);$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,days},null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`life-os-backup-${localDate()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
window.addEventListener('storage',e=>{if(e.key===key){$('save-status').textContent='Archivio modificato in un’altra scheda · ricarica prima di modificare';storageOk=false;}});load(date);
